### ISSUE TITLE
Metric health - is it good or bad?

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#116]
Spamming in a whole lot of people - there must be some good ideas out there...

/cc @labland @ozym @dc735 @quiffman @kfenaugh @sradvan @junghao @bpeng @crleblanc @Colindye 

BB and Xymon use a simple approach to deciding if a metric is good or bad.  They look at the last sample received and decide if its in the thresholds or not.  We've replicated this in mtr/metrics.  I wonder if there is a better (but still simple) way to estimate metric health.

For example this isn't happy but does spend a fair bit of time in the thresholds (the very hard to see grey box in the lowest part of the plot) https://metrics.geonet.org.nz/field/plot?deviceID=strong-lytteltonportcompany&typeID=ping

Is there some other way to quantify metric health?  Most of these populations are long tail (very non normal) so I don't think std deviations would help a lot.  I wonder about something as brutal as % of samples within threshold over a time window.

Suggestions welcome.  Answers with working even more welcome.

-G

**Comment by ozym** [comment]
On a related topic, @dc735 and I have been looking at some of the interactions between thresholds, plotting, and services etc.

It's a bit of a minefield but the two main ideas that stood out were along the lines of:

Devices often have hard limits to some of the metrics we measue. An example here is a recent trimble should run between 9.5 and 28 volts as per the specs (http://trl.trimble.com/docushare/dsweb/Get/Document-689228/022506-128G_NetR9_DS_4pnl_0815_LR.pdf). These are what we are calling __hard__ thresholds for (in this instance __voltage__) for that, and only that, device. We would probably use 10% either side as the actual threshold range.

But, at the same time for a given site we would expect the voltage to be within a certain range - this is likely to be more site specific than instrument - but the thresholds would be more reasonable , i.e. 11.5 to 16.0 (say).  We are calling these __soft__ thresholds, if things move outside of this range the site isn't likely to be broken (or at least the device isn't) but it is sub-optimal. This is likely to be useful for diagnostics rather than alerting.

There are a couple of metrics which have a foot in either door.  For instance __ping__, if a site isn't _pingable_ there's a good chance there's a problem so something may need to be done. However, if a ping is a little slow (i.e. outside normal expected ranges) this may not be a problem but a result of some other action. The ultimate goal here is to use the related _service_ metric (i.e. the data SLA) to determine whether there's a problem. That is, if the site has long pings but the data is coming in within the specified SLA then there really isn't a problem (that needs alerting). However, these long pings may be a symptom of something else and would be useful for diagnostics etc.

So in this instance, we have a lower hard limit (i.e. no ping is bad) but a soft upper limit (i.e. late pings are okay - provided we are checking the service).

Not quite sure how this would fit together, but perhaps we have something along the threshold lines of a `MAXINT` means bad (i.e. no ping, no conn etc). But we can give __hard__ thresholds of upper & lower (but if one, or either, of these is `MAXINT` then perhaps we could ignore the limit).  Somewhere perhaps a new threshold, or a couple of extra options to give an _expected_ or _optimum_ operational range can be given.

Some thinking was that these _optimal_ or _expected_  ranges would be a better starting point for the plotting ranges rather than the _hard_ thresholds which have the tendency to make the plots flat line when the threshold ranges are quite wide.

bit of a brain dump - but we're starting to see how it will work ...

**Comment by ozym** [comment]
@dc735 also mentioned the idea of a metric on a metric, i.e. in this case it would be percentage of time outside the optimal (_soft_) bounds over some longer time interval. If this was too bad over a long period of time then perhaps we can see a problem that needs raising ... whereas small excursions are not a big deal.  The _hard_ thresholds would take care of the really big problems.

**Comment by dc735** [comment]
Also we need to stop using the thresholds to set the y range on the graphs. I think my preference would be to just use the extents of the current data to be shown in the plot

**Comment by gclitheroe** [comment]
@dc735 please could you open a separate issue for this ^^^ ?  It's not really to do with metric health so it's going to get lost on this issue.

**Comment by dc735** [comment]
Done
