### ISSUE TITLE
Protobuf version of JSON services for your consumption

### ISSUE THREAD

**Issue by gclitheroe** [GeoNet/mtr#155]
Hi,

@crleblanc has added protobuf versions of the JSON web services to mtr-api.  They appeared in this commit (and are deployed)

https://github.com/GeoNet/mtr/commit/02e2f714773c2b64b1950e7d296843159d068bf0

Once you've switched over to them could you please let us know an we will pull out the JSON services.

Thanks
Geoff

/cc @dc735

**Comment by ozym** [comment]
I've switched over to protobufs. 

Not sure if @dc735 uses any GET calls but I suspect not.

You're good to remove the json once we have the tick from @dc735 .

**Comment by ozym** [comment]
Only slight issue I had was loading floats, my struct had float64 for lat/lon which loaded via json and compared well with the float64 values derived from the disk files. However, the protobufs were float32 (which is fine) and a simple conversion to float64 didn't play nicely due to rounding etc. when converting back to a striing. Simple solution was to switch to float32 internally in the client.
