### ISSUE TITLE
Metric grouping on one graph

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#168]
To scenarios here.

1. rf.signal & rf.noise - We need to be able to see both these values on one graph to compare them
2. We are looking to deploy an instrument  to monitor voltage that will provide multiple values. These should be plotted on a singe graph

Priority = None assigned

**Comment by crleblanc** [comment]
It should be easy to plot two time series on an interactive graph, since it already supports this.

The slightly more difficult part would be to query both the signal and noise series in a single call.  We could modify fieldMetricCsv()  in mtr-api to accept multiple typeIDs and write a single CSV with a column for each.  We're doing something similar for other plots with multiple time series.  This should be backward compatible.

I'm not 100% what the api changes would involve (most modifying the SQL query) so won't comment on that.

**Comment by crleblanc** [comment]
I've modified the fieldMetricCsv to handle multiple typeIDs.  This is done by specifying multiple params in the URL, eg: "typeID=XYZ&typeID=ABC".  Once the changes to the API are merged it should be a simple task to modify the URLs for /field/plot in mtr-ui to handle any number of typeIDs.
