### ISSUE TITLE
Interactive graphs

### ISSUE THREAD

**Issue by dc735** [GeoNet/mtr#170]
Same functionality as Librato Metrics

Priority = None assigned

**Comment by gclitheroe** [comment]
Seems legit to me.  Please have a look at #165 #166 and #168 before starting.  This could probably address all of those as well.

There will need to be a service added to mtr-api to return information in a suitable format for a plotting package.

Baishan has used and preferred dygraph in other projects http://dygraphs.com/

http://static.geonet.org.nz/dygraph/dygraph-combined.js

I'm not totally sure where the interactive plots should go in the interface.  Maybe on the same page as plots but on an "interactive" tab or do they replace the plots.

I suggest adding the services, adding some interactive plots and then testing on the users to see which we should keep.

**Comment by andrewcowie** [comment]
These dygraphs look really good. That is probably the best interactivity I have seen yet with graphs.

**Comment by crleblanc** [comment]
I agree, the graphs look excellent.  I haven't done much JS so far but this looks like an interesting task.  I'll get advice from Baishan and Soren when I get stuck.

**Comment by crleblanc** [comment]
Some notes:

Our SVG plots are generated by mtr-api and displayed in the html using <img>.

This approach is different from what dygraph typically expects.  After discussing with the team, we're now looking at using dygraph's ability to load CSV data from a URL, or using a function to load data from a protobuf and store in a native array (my preferred approach since it's fast and we have protobufs implemented already).  This should give us a relatively clean approach, keeping any JS code in the mtr-ui html templates.

**Comment by crleblanc** [comment]
Made good progress towards a demo interactive plot.

Slight change in plan.  Google's protobufs from JS are new and poorly documented.  It requires either Closure or CommonJS for packages, both bringing in an unwanted dependency.  For now I'll get something working with a simple CSV file (from mtr-api) and move onto protobufs later if required.

**Comment by crleblanc** [comment]
The data latency plot is now working in my interactive_plots branch.  However, it looks like app_metrics is much more complicated.  This will take a bit of time to support all types of applicationID and groups, since they use different SQL queries and other differences.

I'd like to call the same methods that are used to create the svg's, but it's hard to say how difficult it will be at this stage.

**Comment by crleblanc** [comment]
Slowly getting there.  Current state:

I have working interactive graphs in my branch.  They work really well for the most part, it looks like dygraphs is very capable.  The following issues remain:

* plotting all of the data points (eg: for /app/data) is creating CSV files that are several MB, and there are five of these on a page.  This is taking roughly 7 seconds per plot, some requests appear to be timing out.  This has increased the load on the server.  We probably need to downsample these data, in a similar approach to that used for the SVG.  This should be simple since we're already using the same methods that create the SVGs.  We could investigate a "level of detail" where high resolution data is downloaded once the user zooms in, but this seems far too complex at this stage.
* Time is being plotted in UTC, we should change this to local time.
* We need to differentiate between missing data and points with a value of zero (eg: number of objects).  This should be straightforward.
* We need to implement a csv method for /field/metric.  This one is simple so should be easy to add.

**Comment by crleblanc** [comment]
The large pull request (GeoNet/mtr#213 and others) implements the interactive graphs.

There are still remaining issues (eg: progressive loading of data, possibly switching to protobufs from csv) but the plots are in a reasonable state.

**Comment by crleblanc** [comment]
Just one very small bugfix left for this branch: https://github.com/GeoNet/mtr/pull/216
